### ISSUE TITLE
Cutscene skips loading world assets

### ISSUE THREAD

**Issue by Gawidev** [Tenome/Gurumin-Modding#2]
**Describe the bug**
This is immediately following the previous issue, entering "Radish Woods Eerie Way" for the first time triggers the second Motoro cutscene without anything but the characters being loaded. See attached.
Level loads as expected if you can manage to exit the level then re-enter.

**Screenshots**
[Its a rather funny bug](https://github.com/user-attachments/assets/f45347e1-167a-4874-ac62-3d486d0e380b)

**Save file**
https://mega.nz/folder/5Ts3hY4R#zN8lyBRxMRv8kGLlV6tT-Q the one before last, named gdata203

I'm going to be honest, I'm wondering how much this might be caused by actual filechanges or if this might be the result of some sort of corruption (these savefiles have been through 2 different patch versions by now). Ive tried a clean reinstall of the game + patch already (same result) & I would be willing to start the game from the beginning to verify, but all the cutscenes being fully unskippable would make things quite rather inefficient.
Id be curious, if you still have the save I sent before, upon completing the rock drilling minigame, are you able to reproduce the issue immediately?

**Comment by Tenome** [comment]
Oh man. Well, admittedly I did not playtest it since I was making changes all over the place to the dialogue, but I don't think any changes I made should affect loading assets. I'll test that in a bit.

I replaced all the script fix files with vanilla, and it loads as intended, so now I have to find out what I did to mess that up... Sorry about that.

It must have been the most recent update, because I dropped in 08.25.2024 and it works as intended. Maybe fixing that extra speech bubble from Doug messed up something.

Fixed it. It must've been one of the Google TL'd comments, maybe an extra space or newline snuck in while I was copy-pasting. So I just didn't add those this time. Update in a bit.

https://github.com/Tenome/Gurumin-Modding/releases/tag/10.27.2024

**Comment by Gawidev** [comment]
Very interesting, and no worries lol, this is what bug testing is all about :)
If anything I'm reassured that so far it seems that our experiences are consistent across the steam/GOG versions. That should make things easier.
It is fixed now, so Ill keep testing later today and report back. 👍
