### ISSUE TITLE
JP text and voices

### ISSUE THREAD

**Issue by JWK-147** [Tenome/Gurumin-Modding#8]
Perhaps it's not really an "issue", but more of a request?

I used the "Japanese dub" and "Japanese text" mods, but there are still some things from the English version. Like the prompt "Talk" instead of "話す", menu options and generally every (or most of them?) image that has text. I heard there's a password-locked door in the game and I think it's safe to assume that - if there are changes between the JP and EN versions - it uses the English answer.
And Parin's name can't be in Japanese. If I type "パリン" it just shows "???".
Would it be possible for you to upload the remaining files needed to make the Steam version exactly like the original Japanese PC release? I tried downloading the 2004 version to just copy-paste the files, but it needs to be installed first and for some time at least I won't be able to change my system's locale, which seems to be required.

![20241102114214_1](https://github.com/user-attachments/assets/c5c195e3-c622-4b4f-beed-01a117c99e6c)
![20241102114218_1](https://github.com/user-attachments/assets/b9942a28-d77b-4036-bc33-f4b404f62218)

**Comment by Tenome** [comment]
The menu options are part of the exe, and thus I don't think you can edit them. Not being able to use any JP text in the name should also be for the same reason. You can try swapping out the exe from the original JP release and seeing if that works (don't think it will, though). Here's an upload of the JP version of the game's installation folder.

https://mega.nz/file/IOFRERzL#_bORZxX_ZOJirjxylwbvojIjViyP0bsRZiffu4dv5mY

I ran a directory comparison and copied over the files that were different/exclusive to the JP folder, and updated the JP text patch. No guarantees that everything will work, since some files might be exclusive to the JP version. Stuff like boss and level names should now be in JP if it exists. The "Talk" prompt should also be carried over. The password is stored in map.itm which was swapped out for the JP version, so it should accept the JP password. 

I'll take another look and see if any other menu items can be converted back to JP, but I'm pretty sure that whatever is leftover is stored in the .exe.

**Comment by JWK-147** [comment]
As expected, using the old .exe breaks the game for me. But copying the whole "3ddata" folder brings back some more things. Icons above Parin's head are now in Japanese, like you said, top right icons (パーツ and そうび) as well, but the bottom right prompt is still "Examine" instead of "しらべる". Seems they made a proper mess making the game and/or translating the game.
But well, doesn't need to be perfect. The most important thing are dialogues. I can live with those small inconsistencies. It's not like even some Japanese-only games don't use English words sometimes here and there for no apparent reason.
So for now I'll only add map.itm and see how it goes.
Thanks!

![20241102171650_1](https://github.com/user-attachments/assets/5c618065-b1d0-47af-8c9d-fc7cf58b8606)

**Comment by Tenome** [comment]
I just now updated the JP text patch again since I had to exclude the menu .itm files. You'll need the .itm files from the 3ddata folder too,  those contain cutscene dialogue. The .mmv files should also be safe, those are just the stage and boss names. That should be everything that can be ported over, the rest would require disassembling the .exe or messing with the hex padding to try and replace the words while not breaking the game (don't think I can reliably replace any English text with JP text since JP hex is full-width).

"Examine" is part of the .exe too I think. You can see that the JP prompts are already in the hex, but they aren't being pointed at by the game.

![image](https://github.com/user-attachments/assets/f8301014-4848-457a-97af-6e2a1feb2be7)

**Comment by JWK-147** [comment]
Well, I already copied everything from 3ddata and for now at least it works, so I'll leave it as is and when it breaks, go back to original Steam files and carefully overwrite only the safe ones you listed.
Yeah, shame about the rest, but messing around with the .exe looks like much more work than it's worth. And all that for maybe 2 people a year who want to play the Steam version in Japanese.

Ah, one thing I forgot to mention. I checked a let's play of the 2004 version on Youtube and it doesn't let you name Parin at all, so copying files wouldn't help anyway. Which means that:
1. The code would have to be changed to allow Japanese characters which probably means a load of work, if at all possible.
2. All dialogues would have to be checked and all instances of characters calling her "パリン" changed to whatever the English version uses for the name in dialogues, like "[player_name]" or something, because name isn't a variable in the original.

If anything, it would be faster to remove the ability to name the character altogether. Faster, but still not easy, I bet.

**Comment by Tenome** [comment]
The DLSite version (what I uploaded) lets you rename Parin, so I suspect that they added that as a feature in a later update. I have the original DVD ISO as well ((一般ゲーム) [041225] [日本ファルコム] ぐるみん [修正・NoDVDパッチ付] (iso+mds)) so maybe that's what they were playing.

![capture00002](https://github.com/user-attachments/assets/c57d081b-e55c-4e4e-8527-98282650dd51)

**Comment by JWK-147** [comment]
So there's even more versions, huh. They should just rerelease it one last time, with all languages they have, all content, available for all countries and platforms, and possibly with unlocked fps, or at least locked at 60.
